Mission09_adw97/Components/BasketSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission09_adw97.Models;

namespace Mission09_adw97.Components
{
    public class BasketSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public BasketSummaryViewComponent(Basket b)
        {
            basket = b;
        }

        public IViewComponentResult Invoke()
        {
            return View(basket);
        }

    }

}

Mission09_adw97/Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_adw97.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_adw97.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }
        public TypesViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["categoryType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }



    }

    
}

Mission09_adw97/Views/Shared/BookSummary.cshtml
@model Books
<div class="card card-outline-primary m-1 p-1">

    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <span class="badge bg-info" style="float:right">
            ISBN: @Model.Isbn
        </span>
    </div>
    
    <ul class="list-inline">
        <li>Author: @Model.Author</li>
        <li>Category: @Model.Category</li>
        <li>Publisher: @Model.Publisher</li>
        <li>Price: $@Model.Price</li>
    </ul>

    <form method="post" asp-page="/Purchase">
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Purchase</button>
        </span>
    </form>

</div>

Mission09_adw97/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">Narns and Boble</span>
        <div class="float-end">
            <vc:basket-summary />
        </div>
    </div>
    <div class="row m-1 p-1">
        <!--This is the left side menu with the list of categories to filter by-->
        <div id="categories" class="col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>